openapi: 3.0.1
info:
  title: My To-Do's Google Drive
  version: 1.0.0
paths:
  /read-file:
    get:
      operationId: readDriveFile
      summary: Read a task file from Google Drive
      parameters:
        - name: fileId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File contents retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
      security:
        - oauth2: [drive]
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            drive: Access user files on Google Drive
