{
  "schema_version": "v1",
  "info": {
    "title": "My To-Do's Google Drive",
    "description": "Read task files from a user's Google Drive",
    "version": "1.0.0"
  },
  "name_for_human": "My To-Do's Google Drive",
  "name_for_model": "my_todos_google_drive",
  "auth": {
    "type": "oauth",
    "client_url": "https://accounts.google.com/o/oauth2/v2/auth",
    "authorization_content_type": "application/x-www-form-urlencoded",
    "scope": "https://www.googleapis.com/auth/drive.file",
    "token_url": "https://oauth2.googleapis.com/token"
  },
  "api": {
    "type": "openapi",
    "url": "https://raw.githubusercontent.com/mpopovits/my-todos-gpt-plugin/main/openapi.yaml"
  },
  "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png",
  "contact_email": "michelle@example.com",
  "legal_info_url": "https://example.com/legal",
  "servers": [
    {
      "url": "https://my-todos-api.fly.dev"
    }
  ]
}
